# Generated by Django 4.1.2 on 2022-10-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='courseteacher',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
