# Generated by Django 4.1.2 on 2022-12-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_coursefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.CharField(default='no_image.svg', max_length=25, verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_as_markdown',
            field=models.BooleanField(default=False, verbose_name='Разметка'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='', max_length=256, verbose_name='Описание'),
        ),
    ]
